export const siteConfig = {
  name: "Taskify",
  description: "Collaborate, manage projects and reach new productivity peaks.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "task list",
    "trello clone",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "zustand",
    "query-string",
    "sooner",
    "headlessui",
    "sql",
    "mysql",
    "supabase",
    "prisma",
    "lucide-react",
    "next-pwa",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
} as const;
